name: Cache GitHub Statistics

on:
  schedule:
    - cron: '15 15 * * 1'
  workflow_dispatch:

jobs:
  update-github-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore latest cached stats
        id: cache-stats
        uses: actions/cache@v3
        with:
          path: |
            statistics/streak.svg
            statistics/github.svg
          key: stats-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            stats-${{ runner.os }}-

      - name: Fetch latest streak stats
        run: |
          curl -o statistics/streak.svg "https://github-readme-streak-stats.sherlox.io/?user=kunal-ma&theme=codestackr&hide_border=true&card_width=410"

      - name: Fetch latest GitHub profile stats
        run: |
          curl -o statistics/github.svg "https://github-readme-stats.sherlox.io/api?username=kunal-ma&theme=codeSTACKr&hide_border=true&card_width=410"

      - name: Commit and push the latest stats to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add statistics/github.svg statistics/streak.svg

          if git diff --cached --quiet; then
            echo "No changes detected. Skipping commit."
            exit 0
          fi

          git commit -m "chore(actions): update generated statistics cache"
          git push origin main
